---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true

platforms:
- name: ubuntu-12.04
  driver_config:
    box: opscode-ubuntu-12.04
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box
  run_list:
  - recipe[sphinx::test_prep]
  - recipe[sphinx]

- name: centos-6.4
  driver_config:
    box: opscode-centos-6.4
    box_url: https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_centos-6.4_provisionerless.box
  run_list:
  - recipe[sphinx::test_prep]
  - recipe[sphinx]

suites:
- name: source-install
  run_list:
  - recipe[minitest-handler]
  - recipe[sphinx_test]
  attributes:
    sphinx:
      version: '2.0.8'

- name: package-install
  run_list:
  - recipe[minitest-handler]
  - recipe[sphinx_test]
  attributes:
    sphinx:
      use_package: true
