name             "sphinx"
maintainer       "Alex Soto"
maintainer_email "apsoto@gmail.com"
license          "Apache 2.0"
description      "Installs/Configures sphinx search engine."
long_description IO.read(File.join(File.dirname(__FILE__), 'README.rdoc'))
version          "0.5.0"
provides         "sphinx::default"
provides         "sphinx::package"
provides         "sphinx::source"
depends          "build-essential"
depends          "mysql"
depends          "postgresql"
supports         "centos"
supports         "rhel"
supports         "ubuntu"
supports         "debian"
